In [380]:
import pandas as pd

In [381]:
a = pd.Series(['a','b','c'],[2,2,3])
a

2    a
2    b
3    c
dtype: str

In [382]:
dict = {'a':1,'b':2,'cc':10}
a = pd.Series(dict)
a

a      1
b      2
cc    10
dtype: int64

In [383]:
import numpy as np

In [384]:
a = np.array([1,2,2,4,5])
b1 = pd.Series(a,copy=True)
b2 = pd.Series(a)
print(b1)
a

0    1
1    2
2    2
3    4
4    5
dtype: int64

array([1, 2, 2, 4, 5])

In [385]:
b2

0    1
1    2
2    2
3    4
4    5
dtype: int64

In [386]:
a[1]=100
a

array([  1, 100,   2,   4,   5])

In [387]:
b1

0    1
1    2
2    2
3    4
4    5
dtype: int64

In [388]:
b2

0    1
1    2
2    2
3    4
4    5
dtype: int64

In [389]:
p = pd.Series(a,index=[2,1,3,4,5])
p

2      1
1    100
3      2
4      4
5      5
dtype: int64

In [390]:
p.iloc[1]

np.int64(100)

In [391]:
p.loc[3]+=1
p

2      1
1    100
3      3
4      4
5      5
dtype: int64

In [392]:
p[2]

np.int64(1)

In [393]:
#dataframe
#列
dict_1 = {'s':[1,2,3,4],
          'e':[5,6,7,8],
          'm':[9,8,7,6],
          'mi':[1,1,1,1]}

data = pd.DataFrame(dict_1,['a','b','c','d'])
data

   s  e  m  mi
a  1  5  9   1
b  2  6  8   1
c  3  7  7   1
d  4  8  6   1

In [394]:
dict_2 = {'s':pd.Series([1,2,3,4],['a','b','c','d']),
          'e':pd.Series([5,6,7,8],['a','b','c','d']),
          'm':pd.Series([9,8,7,6],['a','b','c','d']),
          'mi':pd.Series([1,1,1,1],['a','b','c','d'])}
data = pd.DataFrame(dict_2)
data

   s  e  m  mi
a  1  5  9   1
b  2  6  8   1
c  3  7  7   1
d  4  8  6   1

In [395]:
a = np.random.rand(3,3)
data = pd.DataFrame(a,index=['a','b','c'],columns=['s','e','m'])
data

          s         e         m
a  0.196780  0.293109  0.478038
b  0.530943  0.188566  0.382885
c  0.204945  0.507458  0.111482

In [396]:
data['s']

a    0.196780
b    0.530943
c    0.204945
Name: s, dtype: float64

In [397]:
data[1:3]

          s         e         m
b  0.530943  0.188566  0.382885
c  0.204945  0.507458  0.111482

In [398]:
data.m

a    0.478038
b    0.382885
c    0.111482
Name: m, dtype: float64

In [399]:
data.loc['a']

s    0.196780
e    0.293109
m    0.478038
Name: a, dtype: float64

In [400]:
data.iloc[0]

s    0.196780
e    0.293109
m    0.478038
Name: a, dtype: float64

In [401]:
data.loc['a','m']

np.float64(0.47803805864888993)

In [402]:
data.iloc[:2,:2]

          s         e
a  0.196780  0.293109
b  0.530943  0.188566

In [403]:
data.iloc[[0,2],[0,2]]

          s         m
a  0.196780  0.478038
c  0.204945  0.111482

In [404]:
#增加
data

          s         e         m
a  0.196780  0.293109  0.478038
b  0.530943  0.188566  0.382885
c  0.204945  0.507458  0.111482

In [405]:
data['mi'] = np.array([1,1,1])
data

          s         e         m  mi
a  0.196780  0.293109  0.478038   1
b  0.530943  0.188566  0.382885   1
c  0.204945  0.507458  0.111482   1

In [406]:
data['mi2'] = pd.Series([1,1,1],index=['a','b','c'])
data

          s         e         m  mi  mi2
a  0.196780  0.293109  0.478038   1    1
b  0.530943  0.188566  0.382885   1    1
c  0.204945  0.507458  0.111482   1    1

In [407]:
data1 = pd.DataFrame([[2,3,4,5,6],[1,5,7,3,2]],['d','e'],['s','e','m','mi','mi2'])
data1

   s  e  m  mi  mi2
d  2  3  4   5    6
e  1  5  7   3    2

In [408]:
data = pd.concat([data,data1],axis=0)
data

          s         e         m  mi  mi2
a  0.196780  0.293109  0.478038   1    1
b  0.530943  0.188566  0.382885   1    1
c  0.204945  0.507458  0.111482   1    1
d  2.000000  3.000000  4.000000   5    6
e  1.000000  5.000000  7.000000   3    2

In [409]:
data.drop(['e','d'],axis=0)

          s         e         m  mi  mi2
a  0.196780  0.293109  0.478038   1    1
b  0.530943  0.188566  0.382885   1    1
c  0.204945  0.507458  0.111482   1    1

In [410]:
data

          s         e         m  mi  mi2
a  0.196780  0.293109  0.478038   1    1
b  0.530943  0.188566  0.382885   1    1
c  0.204945  0.507458  0.111482   1    1
d  2.000000  3.000000  4.000000   5    6
e  1.000000  5.000000  7.000000   3    2

In [411]:
data.drop(['e'],axis=0,inplace=True)#直接删除

In [412]:
data

          s         e         m  mi  mi2
a  0.196780  0.293109  0.478038   1    1
b  0.530943  0.188566  0.382885   1    1
c  0.204945  0.507458  0.111482   1    1
d  2.000000  3.000000  4.000000   5    6

In [413]:
data.drop(data.index[1])

          s         e         m  mi  mi2
a  0.196780  0.293109  0.478038   1    1
c  0.204945  0.507458  0.111482   1    1
d  2.000000  3.000000  4.000000   5    6

In [414]:
data.values

array([[0.19678036, 0.293109  , 0.47803806, 1.        , 1.        ],
       [0.53094272, 0.18856576, 0.38288456, 1.        , 1.        ],
       [0.20494499, 0.50745755, 0.11148204, 1.        , 1.        ],
       [2.        , 3.        , 4.        , 5.        , 6.        ]])

In [415]:
data.T

            a         b         c    d
s    0.196780  0.530943  0.204945  2.0
e    0.293109  0.188566  0.507458  3.0
m    0.478038  0.382885  0.111482  4.0
mi   1.000000  1.000000  1.000000  5.0
mi2  1.000000  1.000000  1.000000  6.0

In [416]:
data.describe()

              s         e         m   mi   mi2
count  4.000000  4.000000  4.000000  4.0  4.00
mean   0.733167  0.997283  1.243101  2.0  2.25
std    0.858776  1.341726  1.844483  2.0  2.50
min    0.196780  0.188566  0.111482  1.0  1.00
25%    0.202904  0.266973  0.315034  1.0  1.00
50%    0.367944  0.400283  0.430461  1.0  1.00
75%    0.898207  1.130593  1.358529  2.0  2.25
max    2.000000  3.000000  4.000000  5.0  6.00

In [417]:
data.sum()

s      2.932668
e      3.989132
m      4.972405
mi     8.000000
mi2    9.000000
dtype: float64

In [418]:
#var std

In [419]:
data.rename(columns={'s':'A'},inplace=True)
data

          A         e         m  mi  mi2
a  0.196780  0.293109  0.478038   1    1
b  0.530943  0.188566  0.382885   1    1
c  0.204945  0.507458  0.111482   1    1
d  2.000000  3.000000  4.000000   5    6

In [420]:
data.index

Index(['a', 'b', 'c', 'd'], dtype='str')

In [421]:
data.columns

Index(['A', 'e', 'm', 'mi', 'mi2'], dtype='str')

In [422]:
df=data.reindex(index=['a', 'b', 'c'],columns=['A','B'])
df

          A   B
a  0.196780 NaN
b  0.530943 NaN
c  0.204945 NaN

In [423]:
data.reindex(index=['a', 'b', 'c'],columns=['A','B'],fill_value=0)

          A  B
a  0.196780  0
b  0.530943  0
c  0.204945  0

In [ ]:
df.reset_index(inplace=True,drop=True)#不要增加abc列
df

          A   B
0  0.196780 NaN
1  0.530943 NaN
2  0.204945 NaN

In [426]:
df.sort_index()

          A   B
0  0.196780 NaN
1  0.530943 NaN
2  0.204945 NaN

In [427]:
df.sort_values(by='A',ascending=False)

          A   B
1  0.530943 NaN
2  0.204945 NaN
0  0.196780 NaN