In [122]:
import pandas as pd
import numpy as np

In [123]:
df = pd.DataFrame(np.random.rand(5,3),index=['a','b','c','f','h'],columns=['A','C','B'])
df

          A         C         B
a  0.722979  0.876278  0.532578
b  0.427002  0.749806  0.296901
c  0.020428  0.131528  0.462926
f  0.754445  0.854718  0.693150
h  0.099797  0.365598  0.842251

In [124]:
df = df.reindex(index=['a','b','c','d','e','f','g','h'])
df

          A         C         B
a  0.722979  0.876278  0.532578
b  0.427002  0.749806  0.296901
c  0.020428  0.131528  0.462926
d       NaN       NaN       NaN
e       NaN       NaN       NaN
f  0.754445  0.854718  0.693150
g       NaN       NaN       NaN
h  0.099797  0.365598  0.842251

In [125]:
df.isnull().sum()

A    3
C    3
B    3
dtype: int64

In [126]:
df.isnull().sum()/df.shape[0]

A    0.375
C    0.375
B    0.375
dtype: float64

In [127]:
df.isnull().any()

A    True
C    True
B    True
dtype: bool

In [128]:
df.fillna({'A':1},inplace=True)

          A         C         B
a  0.722979  0.876278  0.532578
b  0.427002  0.749806  0.296901
c  0.020428  0.131528  0.462926
d  1.000000       NaN       NaN
e  1.000000       NaN       NaN
f  0.754445  0.854718  0.693150
g  1.000000       NaN       NaN
h  0.099797  0.365598  0.842251

In [129]:
df.ffill()

          A         C         B
a  0.722979  0.876278  0.532578
b  0.427002  0.749806  0.296901
c  0.020428  0.131528  0.462926
d  1.000000  0.131528  0.462926
e  1.000000  0.131528  0.462926
f  0.754445  0.854718  0.693150
g  1.000000  0.854718  0.693150
h  0.099797  0.365598  0.842251

In [130]:
df.bfill()

          A         C         B
a  0.722979  0.876278  0.532578
b  0.427002  0.749806  0.296901
c  0.020428  0.131528  0.462926
d  1.000000  0.854718  0.693150
e  1.000000  0.854718  0.693150
f  0.754445  0.854718  0.693150
g  1.000000  0.365598  0.842251
h  0.099797  0.365598  0.842251

In [131]:
df.dropna()

          A         C         B
a  0.722979  0.876278  0.532578
b  0.427002  0.749806  0.296901
c  0.020428  0.131528  0.462926
f  0.754445  0.854718  0.693150
h  0.099797  0.365598  0.842251

In [132]:
df = pd.read_excel('IPL.xlsx')
df

      Team  Rank  Year  Points
0   Riders     1  2014     876
1   Riders     2  2015     789
2   Devils     2  2014     863
3   Devils     3  2015     673
4    Kings     3  2014     741
5    Kings     4  2015     812
6    Kings     1  2016     756
7    Kings     1  2017     788
8   Riders     2  2016     694
9   Royals     4  2014     701
10  Royals     1  2015     804
11  Riders     2  2017     690

In [133]:
df_year  = df.groupby('Year')
for year,group in df_year:
    print('year{}\n'.format(year))
    print(group)

year2014

     Team  Rank  Year  Points
0  Riders     1  2014     876
2  Devils     2  2014     863
4   Kings     3  2014     741
9  Royals     4  2014     701
year2015

      Team  Rank  Year  Points
1   Riders     2  2015     789
3   Devils     3  2015     673
5    Kings     4  2015     812
10  Royals     1  2015     804
year2016

     Team  Rank  Year  Points
6   Kings     1  2016     756
8  Riders     2  2016     694
year2017

      Team  Rank  Year  Points
7    Kings     1  2017     788
11  Riders     2  2017     690

In [134]:
df_year.get_group(2015)

      Team  Rank  Year  Points
1   Riders     2  2015     789
3   Devils     3  2015     673
5    Kings     4  2015     812
10  Royals     1  2015     804

In [135]:
df_year.agg({'Points':[np.max,np.mean]})

     Points
        max    mean
Year
2014    876  795.25
2015    812  769.50
2016    756  725.00
2017    788  739.00

In [136]:
df_year['Points'].agg([np.max])

      max
Year
2014  876
2015  812
2016  756
2017  788

In [137]:
Zscore = lambda x: (x-x.mean())/x.std()
df['zs']=df_year['Points'].transform(Zscore)

In [138]:
df

      Team  Rank  Year  Points        zs
0   Riders     1  2014     876  0.923501
1   Riders     2  2015     789  0.299834
2   Devils     2  2014     863  0.774826
3   Devils     3  2015     673 -1.483796
4    Kings     3  2014     741 -0.620432
5    Kings     4  2015     812  0.653485
6    Kings     1  2016     756  0.707107
7    Kings     1  2017     788  0.707107
8   Riders     2  2016     694 -0.707107
9   Royals     4  2014     701 -1.077894
10  Royals     1  2015     804  0.530476
11  Riders     2  2017     690 -0.707107

In [ ]:
df_team = df.groupby(by='Team')

In [141]:
tetsfun = lambda x:len(x)>3
df_team.filter(tetsfun)

      Team  Rank  Year  Points        zs
0   Riders     1  2014     876  0.923501
1   Riders     2  2015     789  0.299834
4    Kings     3  2014     741 -0.620432
5    Kings     4  2015     812  0.653485
6    Kings     1  2016     756  0.707107
7    Kings     1  2017     788  0.707107
8   Riders     2  2016     694 -0.707107
11  Riders     2  2017     690 -0.707107